### PR TITLE
Added output when no vulnerabilities are found.

### PR DESCRIPTION
**Pull request by cschiewek**
It's nice to get feedback that everything is good with your Gemfile.lock, it's reassuring, and it confirms the audit is actually running.

### CODE REVIEW

**Comment by cschiewek** [comment]
I didn't think a notification was warranted, but I can add the code to notify as well, if you'd like.

**Comment by christianhellsten** [comment]
Thanks!

**Comment by cschiewek** [comment]
If you could release to rubygems with this patch I'd greatly appreciate it :+1:

**Comment by christianhellsten** [comment]
Github is under DDOS attack:
```
$ git clone https://github.com/christianhellsten/guard-bundler-audit/
Cloning into 'guard-bundler-audit'...
error: RPC failed; result=52, HTTP code = 0
fatal: The remote end hung up unexpectedly
```

I'll try again when I return from vacation :ski:

**Pull request merged**
